In [44]:
import pandas as pd

### Data Types: all objects in python have a type. You can check the type by using the _type()_ function. Here are a few standard ones

In [45]:
type(1.5)

float

In [46]:
type(3)

int

In [47]:
type('abc')

str

In [48]:
type(True)

bool

### You can convert between types

In [49]:
float(1)

1.0

In [50]:
str(1)

'1'

In [51]:
int('9')

9

In [52]:
int(9.9)

9

### DataFrames also have a type

In [53]:
accidents = pd.read_csv('../data/Traffic_Accidents.csv')

In [54]:
type(accidents)

pandas.core.frame.DataFrame

### And each column has a type

In [55]:
accidents.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28173 entries, 0 to 28172
Data columns (total 26 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Accident Number             28173 non-null  int64
 1   Date and Time               28173 non-null  object
 2   Number of Motor Vehicles    28173 non-null  float64
 3   Number of Injuries          28173 non-null  float64
 4   Number of Fatalities        28173 non-null  int64
 5   Property Damage             2588 non-null   object
 6   Hit and Run                 28169 non-null  object
 7   Reporting Officer           28172 non-null  float64
 8   Collision Type Code         28172 non-null  float64
 9   Collision Type Description  28172 non-null  object
 10  Weather Code                23634 non-null  float64
 11  Weather Description         23634 non-null  object
 12  Illumination Code           28127 non-null  float64
 13  Illumination Description    28127 non-null  object
 14  Harmful Code                28173 non-null  object
 15  Harmful Description         27774 non-null  object
 16  Street Address              28173 non-null  object
 17  City                        28173 non-null  object
 18  State                       28173 non-null  object
 19  ZIP                         28162 non-null  float64
 20  RPA                         28163 non-null  float64
 21  Precinct                    28163 non-null  object
 22  Latitude                    28115 non-null  float64
 23  Longitude                   28115 non-null  float64
 24  Mapped Location             28115 non-null  object
 25  date                        28173 non-null  object
dtypes: float64(10), int64(2), object(14)
memory usage: 5.6+ MB

In [56]:
accidents.dtypes

Accident Number                 int64
Date and Time                  object
Number of Motor Vehicles      float64
Number of Injuries            float64
Number of Fatalities            int64
Property Damage                object
Hit and Run                    object
Reporting Officer             float64
Collision Type Code           float64
Collision Type Description     object
Weather Code                  float64
Weather Description            object
Illumination Code             float64
Illumination Description       object
Harmful Code                   object
Harmful Description            object
Street Address                 object
City                           object
State                          object
ZIP                           float64
RPA                           float64
Precinct                       object
Latitude                      float64
Longitude                     float64
Mapped Location                object
date                           object
dtype: object

In [57]:
accidents.head()

,Accident Number,Date and Time,Number of Motor Vehicles,Number of Injuries,Number of Fatalities,Property Damage,Hit and Run,Reporting Officer,Collision Type Code,Collision Type Description,...,Street Address,City,State,ZIP,RPA,Precinct,Latitude,Longitude,Mapped Location,date
0,20200000247,2020-01-01 00:25:00,2.0,0.0,0,NaN,True,109543.0,5.0,SIDESWIPE - SAME DIRECTION,...,6TH AVN & MADISON ST,NASHVILLE,TN,37208.0,4305.0,NORTH,36.1750,-86.7894,POINT (-86.7894 36.175),2020-01-01
1,20200000511,2020-01-01 00:30:00,2.0,0.0,0,NaN,True,279217.0,11.0,Front to Rear,...,9TH AVN & JEFFERSON ST,NASHVILLE,TN,37208.0,4239.0,NORTH,36.1730,-86.7924,POINT (-86.7924 36.173),2020-01-01
2,20200000105,2020-01-01 00:35:00,2.0,2.0,0,NaN,False,110062.0,4.0,ANGLE,...,MM 47 1 I 24,NASHVILLE,TN,37207.0,1904.0,CENTRA,36.1870,-86.7760,POINT (-86.776 36.187),2020-01-01
3,20200000203,2020-01-01 01:03:00,2.0,0.0,0,NaN,False,226175.0,11.0,Front to Rear,...,MM 200 6 I 40,NASHVILLE,TN,37209.0,4708.0,WEST,36.1261,-86.9040,POINT (-86.904 36.1261),2020-01-01
4,20200000229,2020-01-01 01:25:00,2.0,1.0,0,NaN,False,224437.0,11.0,Front to Rear,...,VICTORY AV & S 1ST ST,NASHVILLE,TN,37213.0,1101.0,CENTRA,36.1649,-86.7702,POINT (-86.7702 36.1649),2020-01-01

### One data type you will encounter is a `datetime`

### The `Date and Time` column in the `accidents` dataframe is treated as an `object` but we can convert it to a different type, such as a `datetime`

In [58]:
# Let's convert the 'Date and Time' column to a datetime and assign it back to itself
accidents['Date and Time'] = pd.to_datetime(accidents['Date and Time'])

# pd.to_datetime will infer the different date and time components of the string.
# If the datetime is in a strange format or you want to be explicit you can use the 'format' argument
# You will have to use datetime symbols: 
# https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior

# It will take a second to run...

In [59]:
# Now the column is a datetime64[ns]
accidents.dtypes

Accident Number                        int64
Date and Time                 datetime64[ns]
Number of Motor Vehicles             float64
Number of Injuries                   float64
Number of Fatalities                   int64
Property Damage                       object
Hit and Run                           object
Reporting Officer                    float64
Collision Type Code                  float64
Collision Type Description            object
Weather Code                         float64
Weather Description                   object
Illumination Code                    float64
Illumination Description              object
Harmful Code                          object
Harmful Description                   object
Street Address                        object
City                                  object
State                                 object
ZIP                                  float64
RPA                                  float64
Precinct                              object
Latitude                             float64
Longitude                            float64
Mapped Location                       object
date                                  object
dtype: object

In [60]:
# The values in the Date and Time column look different now
accidents.head()

,Accident Number,Date and Time,Number of Motor Vehicles,Number of Injuries,Number of Fatalities,Property Damage,Hit and Run,Reporting Officer,Collision Type Code,Collision Type Description,...,Street Address,City,State,ZIP,RPA,Precinct,Latitude,Longitude,Mapped Location,date
0,20200000247,2020-01-01 00:25:00,2.0,0.0,0,NaN,True,109543.0,5.0,SIDESWIPE - SAME DIRECTION,...,6TH AVN & MADISON ST,NASHVILLE,TN,37208.0,4305.0,NORTH,36.1750,-86.7894,POINT (-86.7894 36.175),2020-01-01
1,20200000511,2020-01-01 00:30:00,2.0,0.0,0,NaN,True,279217.0,11.0,Front to Rear,...,9TH AVN & JEFFERSON ST,NASHVILLE,TN,37208.0,4239.0,NORTH,36.1730,-86.7924,POINT (-86.7924 36.173),2020-01-01
2,20200000105,2020-01-01 00:35:00,2.0,2.0,0,NaN,False,110062.0,4.0,ANGLE,...,MM 47 1 I 24,NASHVILLE,TN,37207.0,1904.0,CENTRA,36.1870,-86.7760,POINT (-86.776 36.187),2020-01-01
3,20200000203,2020-01-01 01:03:00,2.0,0.0,0,NaN,False,226175.0,11.0,Front to Rear,...,MM 200 6 I 40,NASHVILLE,TN,37209.0,4708.0,WEST,36.1261,-86.9040,POINT (-86.904 36.1261),2020-01-01
4,20200000229,2020-01-01 01:25:00,2.0,1.0,0,NaN,False,224437.0,11.0,Front to Rear,...,VICTORY AV & S 1ST ST,NASHVILLE,TN,37213.0,1101.0,CENTRA,36.1649,-86.7702,POINT (-86.7702 36.1649),2020-01-01

In [61]:
# And we can see each value is a timestamp
accidents.loc[0, 'Date and Time']

Timestamp('2020-01-01 00:25:00')

### Once you have a `datetime` object, you can pull out [individual parts](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.dt.html)
- Use `.dt` to specify a datetime attribute/function and then what you want to pull out
- Pull out the month from the 'Date and Time' column and save it to a new column called 'month'

In [62]:
accidents['month'] = accidents['Date and Time'].dt.month
accidents.head()

,Accident Number,Date and Time,Number of Motor Vehicles,Number of Injuries,Number of Fatalities,Property Damage,Hit and Run,Reporting Officer,Collision Type Code,Collision Type Description,...,City,State,ZIP,RPA,Precinct,Latitude,Longitude,Mapped Location,date,month
0,20200000247,2020-01-01 00:25:00,2.0,0.0,0,NaN,True,109543.0,5.0,SIDESWIPE - SAME DIRECTION,...,NASHVILLE,TN,37208.0,4305.0,NORTH,36.1750,-86.7894,POINT (-86.7894 36.175),2020-01-01,1
1,20200000511,2020-01-01 00:30:00,2.0,0.0,0,NaN,True,279217.0,11.0,Front to Rear,...,NASHVILLE,TN,37208.0,4239.0,NORTH,36.1730,-86.7924,POINT (-86.7924 36.173),2020-01-01,1
2,20200000105,2020-01-01 00:35:00,2.0,2.0,0,NaN,False,110062.0,4.0,ANGLE,...,NASHVILLE,TN,37207.0,1904.0,CENTRA,36.1870,-86.7760,POINT (-86.776 36.187),2020-01-01,1
3,20200000203,2020-01-01 01:03:00,2.0,0.0,0,NaN,False,226175.0,11.0,Front to Rear,...,NASHVILLE,TN,37209.0,4708.0,WEST,36.1261,-86.9040,POINT (-86.904 36.1261),2020-01-01,1
4,20200000229,2020-01-01 01:25:00,2.0,1.0,0,NaN,False,224437.0,11.0,Front to Rear,...,NASHVILLE,TN,37213.0,1101.0,CENTRA,36.1649,-86.7702,POINT (-86.7702 36.1649),2020-01-01,1

#### What is the maximum number of cars involved in a single accident in July?
- subset the `accidents` DataFrame to get the July accidents
- find the maximum `Number of Motor Vehicles` for accidents that happened in July

In [63]:
july_accidents = accidents[accidents['month']==7]
july_accidents.head()

,Accident Number,Date and Time,Number of Motor Vehicles,Number of Injuries,Number of Fatalities,Property Damage,Hit and Run,Reporting Officer,Collision Type Code,Collision Type Description,...,City,State,ZIP,RPA,Precinct,Latitude,Longitude,Mapped Location,date,month
11794,20200438614,2020-07-01 00:00:00,2.0,0.0,0,NaN,True,256495.0,9.0,UNKNOWN,...,NASHVILLE,TN,37208.0,4487.0,NORTH,36.1875,-86.8169,POINT (-86.8169 36.1875),2020-07-01,7
11795,20200436762,2020-07-01 00:00:00,1.0,0.0,0,True,True,409221.0,0.0,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,...,ANTIOCH,TN,37013.0,8765.0,SOUTH,36.1969,-86.7929,POINT (-86.7929 36.1969),2020-07-01,7
11796,20200436723,2020-07-01 00:00:00,1.0,0.0,0,True,True,409208.0,9.0,UNKNOWN,...,NASHVILLE,TN,37221.0,4806.0,WEST,36.0950,-86.9373,POINT (-86.9373 36.095),2020-07-01,7
11797,20200436661,2020-07-01 00:03:00,1.0,0.0,0,True,False,256502.0,0.0,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,...,MADISON,TN,37115.0,1627.0,MADISO,36.2619,-86.7033,POINT (-86.7033 36.2619),2020-07-01,7
11798,20200436745,2020-07-01 00:15:00,2.0,0.0,0,NaN,True,332215.0,11.0,Front to Rear,...,NASHVILLE,TN,37209.0,52040.0,WEST,36.1549,-86.8305,POINT (-86.8305 36.1549),2020-07-01,7

In [64]:
july_accidents['Number of Motor Vehicles'].max()

7.0

In [65]:
july_accidents.nlargest(1, 'Number of Motor Vehicles')

,Accident Number,Date and Time,Number of Motor Vehicles,Number of Injuries,Number of Fatalities,Property Damage,Hit and Run,Reporting Officer,Collision Type Code,Collision Type Description,...,City,State,ZIP,RPA,Precinct,Latitude,Longitude,Mapped Location,date,month
11929,20200442999,2020-07-04 00:46:00,7.0,3.0,0,True,False,320578.0,98.0,OTHER,...,NASHVILLE,TN,37211.0,8711.0,SOUTH,36.0667,-86.7179,POINT (-86.7179 36.0667),2020-07-04,7

In [66]:
# How many accidents happened in December?
(accidents['month']==12).sum()

np.int64(1515)

### There are [many different attributes associated with datetimes](https://towardsdatascience.com/working-with-datetime-in-pandas-dataframe-663f7af6c587)

In [67]:
accidents['Date and Time'].dt.time.head()

0    00:25:00
1    00:30:00
2    00:35:00
3    01:03:00
4    01:25:00
Name: Date and Time, dtype: object

In [68]:
accidents['Date and Time'].dt.date.head()

0    2020-01-01
1    2020-01-01
2    2020-01-01
3    2020-01-01
4    2020-01-01
Name: Date and Time, dtype: object

In [69]:
accidents['Date and Time'].dt.weekday.head()

0    2
1    2
2    2
3    2
4    2
Name: Date and Time, dtype: int32

In [70]:
accidents['Date and Time'].dt.is_leap_year.head()

0    True
1    True
2    True
3    True
4    True
Name: Date and Time, dtype: bool

### You can use comparison symbols on `datetime` objects as well

In [71]:
# How many accidents happened before March 3
sum(accidents['Date and Time'] < '03/03/2019')

# Note: You have to input the comparison value as a string,
# but the format can vary and pandas will attempt to infer the format.
# Try putting in different formats and rerunning this cell.

0

### You can also perform calculations on `datetime` objects

In [72]:
# How long between the 1st and 101th accident?
accidents = accidents.sort_values('Date and Time')
accidents.loc[100, 'Date and Time'] - accidents.loc[0, 'Date and Time']

# It appears as a Timedelta, or a change in time

Timedelta('1 days 13:53:00')

# End of Instruction

### Use PGAdmin to get the player info for all players, if they are in the Hall of fame, also pull that data.   
### Save those results as a .csv and read them into this notebook in the cell below

In [73]:
baseball = pd.read_csv('../data/baseball.csv')

baseball.columns

Index(['playerid,"birthyear","birthmonth","birthday","birthcountry","birthstate","birthcity","deathyear","deathmonth","deathday","deathcountry","deathstate","deathcity","namefirst","namelast","namegiven","weight","height","bats","throws","debut","finalgame","retroid","bbrefid","yearid","votedby","ballots","needed","votes","inducted","category","needed_note"'], dtype='object')

### Convert the debut and final game info into Datetime

In [74]:
baseball["debut"] = pd.to_datetime(baseball["debut"])
baseball['finalgame']= pd.to_datetime(baseball['finalgame'])

KeyError: 'debut'

### Find the difference in bebut and final game for all players

In [75]:
baseball['difference'] =baseball['finalgame']-baseball['debut']

KeyError: 'finalgame'

### Next compare that difference among all players, hall of fame players, and players not in the hall of fame